/*********************************************************************
  This file was generated by backbone-typescript-accessor-generator.
  Do not modify it directly!  Subclass the classes defined here to add
  functionality, and use only the subclasses, never those defined here.
 *********************************************************************/

<% models.forEach(function(model){ %>

class _<%= model.name %> extends Backbone.Model {
  <% model.members.forEach(function(member){ %>

    public get_<%=member.name%>() : <%=member.type.typename%> { return this.get('<%=member.name%>'); }

    <% if (!member.readonly) { %>
    public set_<%=member.name%>(val : <%=member.type.typename%>) : void {
      this.set('<%=member.name%>', val);
    }
    <% } %>

  <% }); %>

  static fromJSON(json) : <%= model.name %> {
    var attributes = {};
    <% model.members.forEach(function(member){ %>
      if ('<%= member.name %>' in json) {
          attributes['<%= member.name %>'] = <%= deserialized(member.type, 'json["' + member.name + '"]') %>;
      }
      <% if (!member.optional) { %>
      else {
        throw 'JSON failed validation';
      }
      <% } %>
    <% }); %>
    return new <%= model.name %>(attributes);
  }
}

<% }); %>
